services:
    mongodb:
        image: mongo:7.0
        restart: unless-stopped
        environment:
            MONGO_INITDB_DATABASE: survey
        volumes:
            - mongodb_data:/data/db
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

    app:
        build:
            context: .
            dockerfile: Dockerfile.backend
        environment:
            MONGODB_URI: ${MONGODB_URI:-mongodb://mongodb:27017/survey}
            PORT: 5050
            NODE_ENV: production
            ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
        ports:
            - '80:5050'  # Map internal 5050 to external 80 for direct access
        restart: unless-stopped
        depends_on:
            - mongodb
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
        volumes:
            - uploads:/app/uploads
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5050/api/surveys"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    mongodb_data:
    uploads: